# Generated by Django 5.2.4 on 2025-07-13 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='name_of_dish',
            new_name='dishes_name',
        ),
    ]
