# Generated by Django 5.2.4 on 2025-07-13 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_name_of_dish_dishes_dishes_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dishes',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='dishes_category',
            options={'ordering': ['id'], 'verbose_name': 'Категория блюда', 'verbose_name_plural': 'Категории блюд'},
        ),
        migrations.AlterField(
            model_name='dishes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dishes_category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='dishes_name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='dishes',
            name='photo',
            field=models.ImageField(upload_to='dishes/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='dishes_category',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Категория блюда'),
        ),
    ]
